[supabase]
url = "https://zybakxpyibubzjhzdcwl.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5YmFreHB5aWJ1YnpqaHpkY3dsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDg5NDIwOCwiZXhwIjoyMDcwNDcwMjA4fQ.DJ_Igb6VbPHb999Di87YrHJEwNrI4PC6NcaYNW-HM1w"

[owner]
username = "ganesh"
password_hash = "$2b$12$.Ew6T3bdo4f4XsYiUC7u6uCN9KeLHtxlQFYXwb8v8VFDvFRfUIrfS"
